# Generated by Django 4.2.1 on 2024-07-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeopardTraces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.TextField(default=1)),
                ("long", models.TextField(default=1)),
                ("place", models.TextField(default="n/a")),
                ("description", models.TextField(default="n/a")),
            ],
        ),
    ]
