# Generated by Django 4.2.1 on 2024-07-24 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("traces", "0002_device_leopardtraces_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="device_name",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=100, unique=True
            ),
            preserve_default=False,
        ),
    ]
