# Generated by Django 4.2.1 on 2024-07-24 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("traces", "0003_device_device_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="leopardtraces",
            name="traced_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
