# Generated by Django 4.2.1 on 2024-08-07 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("traces", "0004_leopardtraces_traced_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leopardtraces",
            old_name="description",
            new_name="area_code",
        ),
        migrations.RenameField(
            model_name="leopardtraces",
            old_name="place",
            new_name="confidence",
        ),
        migrations.AddField(
            model_name="device",
            name="cpu_usage",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=100, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="disk_usage",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=100, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="memory_usage",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=100, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="temperature",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=100, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leopardtraces",
            name="type",
            field=models.TextField(default=1),
        ),
    ]
