# Generated by Django 4.2.1 on 2024-08-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traces", "0005_rename_description_leopardtraces_area_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="cpu_usage",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="device",
            name="disk_usage",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="device",
            name="memory_usage",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="device",
            name="temperature",
            field=models.CharField(max_length=100),
        ),
    ]
